name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add permission
      run: chmod +x ./gradlew
    - name: Assemble with Gradle
      run: ./gradlew assembleDebug
    - name: Create directory if not exist
      run: mkdir -p ./apk
    - name: Copy apk
      run: cp ./app/build/outputs/apk/debug/*.apk ./apk/
    - name: Commit & push changes
      run: |
        git add ./apk/*.apk
        result="$(git diff --stat --cached master)"
        if [ "" != "${result}" ]
        then
          git config user.email "action@github.com"
          git config user.name "GitHub Actions CI"
          git commit -m "CI: Automated build push"
          git push origin master
        fi
